version: '3.1'

services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mini_blog
    ports:
      - "5432:5432"
