apiVersion: v1
kind: Service
metadata:
  labels:
    app: mini-blog
  name: mini-blog
  namespace: gcnyin
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: mini-blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-blog
  labels:
    app: mini-blog
  namespace: gcnyin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-blog
  template:
    metadata:
      labels:
        app: mini-blog
    spec:
      containers:
        - name: mini-blog
          image: mini-blog:0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_SERVICE_NAME
              value: mini-blog
            - name: OTEL_TRACES_EXPORTER
              value: jaeger
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: http://jaeger-instance-collector.gcnyin.svc.cluster.local:14250
            - name: JAVA_OPTS
              value: "-Xmx1024M -Dconfig.resource=application-prod.conf"
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
            periodSeconds: 5
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
            periodSeconds: 5
            initialDelaySeconds: 10
          startupProbe:
            httpGet:
              path: /health-check
              port: http
            periodSeconds: 5
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 1G
