apiVersion: v1
kind: Service
metadata:
  labels:
    app: mini-blog
  name: mini-blog
  namespace: gcnyin
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: mini-blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-blog
  labels:
    app: mini-blog
  namespace: gcnyin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-blog
  template:
    metadata:
      labels:
        app: mini-blog
    spec:
      containers:
        - name: mini-blog
          image: mini-blog:0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_SERVICE_NAME
              value: mini-blog
            - name: OTEL_TRACES_EXPORTER
              value: jaeger
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: http://jaeger-instance-collector.gcnyin.svc.cluster.local:14250
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport"
            - name: DB_HOST
              value: postgres-loadbalancer.gcnyin.svc.cluster.local
            - name: DB_URL
              value: jdbc:postgresql://postgres-loadbalancer.gcnyin.svc.cluster.local:5432/hello_world
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: 0s5h3E3O
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
            periodSeconds: 5
            initialDelaySeconds: 5
          startupProbe:
            httpGet:
              path: /health-check
              port: http
            periodSeconds: 5
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 1G
