apiVersion: v1
kind: Service
metadata:
  name: postgres-loadbalancer
  namespace: gcnyin
spec:
  selector:
    app: postgres-database
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-database
  namespace: gcnyin
spec:
  selector:
    matchLabels:
      app: postgres-database
  serviceName: postgres-service
  replicas: 1
  template:
    metadata:
      namespace: gcnyin
      labels:
        app: postgres-database
    spec:
      containers:
        - name: postgres-database
          image: postgres:14.2
          volumeMounts:
            - name: postgres-disk
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: 0s5h3E3O
            - name: POSTGRES_DB
              value: hello_world
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
  volumeClaimTemplates:
    - metadata:
        name: postgres-disk
        namespace: gcnyin
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
